# Name of your site 
name: Synergis

# Short description (goes below the title; it will also be used in the RSS feed)
description: the GIS user group for Ithaca, NY

# Your name, as you want it to appear underneath each post and in the footer
author: Keith Jenkins

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl:

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://synergis-ny.github.io/

# Time zone to use for timestamps
timezone: America/New_York


#### Under the Hood Stuff #####

# Using kramdown as the markdown engine, to support PHP Markdown Extra and other extensions
markdown: kramdown

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md]
